site_name: How to Contribute
#site_description: TODO: Uncomment and change to your site description Ex:'Analysis Modules for Environmental Data Science'
#site_author: TODO: Uncomment and change to your site author(s) Ex: ESIIL CI team (lead = Ty Tuff)
#site_url: TODO: Uncomment and change to your site url Ex: https://cu-esiil.github.io/analytics-library

# Repository
#repo_name: TODO: Uncomment and change this to your repositories name Ex: analytics-library
#repo_url: TODO: Uncomment and change this to your repositories url https://github.com/cu-esiil/analytics-library
# edit_uri is disabled until repo_url is set
# edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2023 University of Colorado Boulder'

# Page tree
nav:
  - Home: index.md
  - Start contributing:
      - Contribute to OASIS: contribute-oasis.md
      - Contribute to the Data Library: contribute-data-library.md
      - Contribute to the Analytics Library: contribute-analytics-library.md
  # TODO: Add your nav sections / sub-sections and path to markdown page Ex:
  # - Remote Sensing:
  #     - How to Cloud Correct Sentinel-2 Images: remote_sensing/sentinel_2_cloud_correction/sentinel_2_cloud_correction.md

# Configuration
theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  #logo: # TODO: Uncomment and add path to your logo .png Ex: 'assets/ESIIL_logo.png'
  #favicon: # TODO: Uncomment and add path to your favicon .png Ex: 'assets/favicon.ico'
  # setting features for the navigation tab
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - search.suggest
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      # link: # TODO: Uncomment and change to your github pages URL Ex: https://cu-esiil.github.io/analytics-library

extra_css:
  - stylesheets/extra.css
  - assets/cta.css

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
